import { setupServer } from 'msw/node';
import { afterAll, afterEach, beforeAll, describe, expect, it } from 'vitest';

import { handlers } from '@/mocks/handlers';

const server = setupServer(...handlers);

beforeAll(() => server.listen({ onUnhandledRequest: 'error' }));
afterEach(() => server.resetHandlers());
afterAll(() => server.close());

describe('GET /api/transactions', () => {
  it('returns a non-empty array of transactions', async () => {
    const res = await fetch('/api/transactions');

    expect(res.ok).toBe(true);
    const body = await res.json();

    expect(Array.isArray(body.data)).toBe(true);
    expect(body.data.length).toBeGreaterThan(0);
  });

  it('each transaction has required fields', async () => {
    const res = await fetch('/api/transactions');
    const body = await res.json();

    for (const tx of body.data) {
      expect(tx).toHaveProperty('id');
      expect(tx).toHaveProperty('amount');
      expect(tx).toHaveProperty('currency');
      expect(tx).toHaveProperty('date');
      expect(tx).toHaveProperty('status');
    }
  });
});

describe('POST /api/transactions/:id/retry', () => {
  it('returns 404 for unknown transaction id', async () => {
    const res = await fetch('/api/transactions/unknown_id/retry', {
      method: 'POST',
    });

    expect(res.status).toBe(404);
  });

  it('returns success or failed status for a known failed transaction', async () => {
    // 19983334 is the first failed transaction generated by the seeded mock data
    const res = await fetch('/api/transactions/19983334/retry', {
      method: 'POST',
    });

    expect(res.ok).toBe(true);
    const body = await res.json();

    expect(body.id).toBe('19983334');
    expect(['success', 'failed']).toContain(body.status);
  });
});

describe('GET /api/transactions/:id/invoice', () => {
  it('returns 404 for unknown transaction id', async () => {
    const res = await fetch('/api/transactions/unknown_id/invoice');

    expect(res.status).toBe(404);
  });

  it('returns a blob with invoice content for a known transaction', async () => {
    // 95163208 is the first transaction generated by the seeded mock data
    const res = await fetch('/api/transactions/95163208/invoice');

    expect(res.ok).toBe(true);
    const text = await res.text();

    expect(text).toContain('95163208');
    expect(text).toContain('INVOICE');
  });
});
